apiVersion: v1
kind: Secret
metadata:
  namespace: litellm
  name: postgres
data:
  # Password for the "postgres" user
  postgres-password: <base64-encoded-password>
  username: <base64-encoded-username>
  password: <base64-encoded-password>
type: Opaque